### ISSUE TITLE
extract-mg Dependency Conflict

### ISSUE THREAD

**Issue by Zamanry** [blacklanternsecurity/MANSPIDER#18]
Running Kali Linux 2022.01 running. Python 3.9.10. APT is fully up-to-date. Proxychains works just fine. I am not using pipx. I activated a venv, git cloned the repo, and then ran the following:
```
sudo proxychains python3 -m pip install -r requirements
... # everything installed correctly until...
Collecting argcomplete==1.10.3
  Using cached argcomplete-1.10.3-py2.py3-none-any.whl (36 kB)
ERROR: Cannot install -r requirements.txt (line 417) and extract-msg==0.29.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested extract-msg==0.29.0
    textract 1.6.4 depends on extract-msg<=0.29.*

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

If you need more information, let me know.

**Comment by QU35T-code** [comment]
Hello,

I have the same issue when I try to install with pipx.

* Python 3.9.2

```bash
root@06e75cdfbbd5:/# python3 -m pipx install git+https://github.com/blacklanternsecurity/MANSPIDER

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/pipx/__main__.py", line 14, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/pipx/main.py", line 819, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/usr/local/lib/python3.9/dist-packages/pipx/main.py", line 202, in run_pipx_command
    return commands.install(
  File "/usr/local/lib/python3.9/dist-packages/pipx/commands/install.py", line 60, in install
    venv.install_package(
  File "/usr/local/lib/python3.9/dist-packages/pipx/venv.py", line 244, in install_package
    self._update_package_metadata(
  File "/usr/local/lib/python3.9/dist-packages/pipx/venv.py", line 318, in _update_package_metadata
    venv_package_metadata = self.get_venv_metadata_for_package(
  File "/usr/local/lib/python3.9/dist-packages/pipx/venv.py", line 300, in get_venv_metadata_for_package
    venv_metadata = inspect_venv(
  File "/usr/local/lib/python3.9/dist-packages/pipx/venv_inspect.py", line 251, in inspect_venv
    app_paths_of_dependencies = _dfs_package_apps(
  File "/usr/local/lib/python3.9/dist-packages/pipx/venv_inspect.py", line 142, in _dfs_package_apps
    app_paths_of_dependencies = _dfs_package_apps(
  File "/usr/local/lib/python3.9/dist-packages/pipx/venv_inspect.py", line 121, in _dfs_package_apps
    dependencies = get_package_dependencies(
  File "/usr/local/lib/python3.9/dist-packages/pipx/venv_inspect.py", line 54, in get_package_dependencies
    for req in map(Requirement, dist.requires or []):
  File "/usr/local/lib/python3.9/dist-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    extract-msg (<=0.29.*)
```

**Comment by TheTechromancer** [comment]
This is due to an issue in our upstream dependency `textract`, which has fallen into disrepair. I am working on fixing it.

A pull request to fix the issue has been open for nearly a year now, without any activity: https://github.com/deanmalmgren/textract/pull/433.

**Comment by TheTechromancer** [comment]
This is fixed in https://github.com/blacklanternsecurity/MANSPIDER/commit/0dc16dbb335df68ae5de932934d1766ed6292950.
