### ISSUE TITLE
Got some error with installing with pipx

### ISSUE THREAD

**Issue by TAI-REx** [blacklanternsecurity/MANSPIDER#25]
cat /proc/version
Linux version 5.4.0-121-generic (buildd@lcy02-amd64-013) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022

>pipx install git+https://github.com/blacklanternsecurity/MANSPIDER
  installed package man-spider 1.0.4, installed using Python 3.8.10
  These apps are now globally available
    - manspider
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in
    your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨

> manspider
Traceback (most recent call last):
  File "/root/.local/bin/manspider", line 5, in <module>
    from man_spider.manspider import main
  File "/root/.local/pipx/venvs/man-spider/lib/python3.8/site-packages/man_spider/manspider.py", line 8, in <module>
    from .lib import *
  File "/root/.local/pipx/venvs/man-spider/lib/python3.8/site-packages/man_spider/lib/__init__.py", line 1, in <module>
    from .parser import *
  File "/root/.local/pipx/venvs/man-spider/lib/python3.8/site-packages/man_spider/lib/parser/__init__.py", line 1, in <module>
    from .parser import *
  File "/root/.local/pipx/venvs/man-spider/lib/python3.8/site-packages/man_spider/lib/parser/parser.py", line 2, in <module>
    import magic
  File "/root/.local/pipx/venvs/man-spider/lib/python3.8/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/root/.local/pipx/venvs/man-spider/lib/python3.8/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by TAI-REx** [comment]
with poetry some here:
root@vps3456 ~/MANSPIDER/man_spider # poetry run manspider
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/MANSPIDER/man_spider/manspider.py", line 8, in <module>
    from .lib import *
  File "/root/MANSPIDER/man_spider/lib/__init__.py", line 1, in <module>
    from .parser import *
  File "/root/MANSPIDER/man_spider/lib/parser/__init__.py", line 1, in <module>
    from .parser import *
  File "/root/MANSPIDER/man_spider/lib/parser/parser.py", line 2, in <module>
    import magic
  File "/root/.cache/pypoetry/virtualenvs/man-spider-MYRw2uSy-py3.8/lib/python3.8/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/root/.cache/pypoetry/virtualenvs/man-spider-MYRw2uSy-py3.8/lib/python3.8/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by kukudemajia** [comment]
pipx runpip man-spider install python-magic-bin==0.4.14
It works.
